# Generated by Django 3.0.4 on 2020-04-11 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='My default Blog', max_length=255),
        ),
    ]
