# Generated by Django 3.0.4 on 2020-05-13 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0016_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
