# Generated by Django 3.0.4 on 2020-05-25 14:23

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0020_auto_20200519_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=0, size=[700, 500], upload_to='BlogSite/media/'),
        ),
    ]
